language: go

go:
  - 1.7
  - 1.8
  - tip

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout 84607742b10f492430762d038e954236bbaf23f7 && go install && cd -
  - glide install
  - go get github.com/mattn/goveralls
  - ./travis-install-configfile.sh

script:
  - go test -v -covermode=count -coverprofile=coverage.out --tags integration
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
